/**
 * bibtex-tidy v1.14.0
 * https://github.com/FlamingTempura/bibtex-tidy
 *
 * DO NOT EDIT THIS FILE. This file is automatically generated
 * using `npm run build`. Edit files in './src' then rebuild.
 **/

var __defProp = Object.defineProperty;
var __name = (target, value) => __defProp(target, "name", { value, configurable: true });

// src/parsers/latexParser.ts
var BlockNode = class _BlockNode {
  constructor(kind, parent, children = []) {
    this.type = "block";
    this.kind = kind;
    this.parent = parent;
    this.children = children;
    if (parent instanceof _BlockNode) {
      parent.children.push(this);
    } else if (parent instanceof CommandNode) {
      parent.args.push(this);
    }
  }
  static {
    __name(this, "BlockNode");
  }
  renderAsText() {
    return this.children.map((child) => child.renderAsText()).join("");
  }
};
var TextNode = class {
  constructor(parent, text = "") {
    this.type = "text";
    this.parent = parent;
    this.text = text;
    parent.children.push(this);
  }
  static {
    __name(this, "TextNode");
  }
  renderAsText() {
    return this.text.replace(/"/g, "");
  }
};
var CommandNode = class {
  constructor(parent, command = "", args = []) {
    this.type = "command";
    this.parent = parent;
    this.command = command;
    this.args = args;
    parent.children.push(this);
  }
  static {
    __name(this, "CommandNode");
  }
  renderAsText() {
    return this.args.map((arg) => arg.renderAsText()).join("");
  }
};
function parseLaTeX(input) {
  const rootNode = new BlockNode("root");
  let node = rootNode;
  for (let i = 0; i < input.length; i++) {
    const char = input[i];
    if (!char) break;
    switch (node.type) {
      case "block": {
        if (char === "\\") {
          node = new CommandNode(node);
        } else if (char === "{") {
          node = new BlockNode("curly", node);
        } else if ((char === "}" && node.kind === "curly" || char === "]" && node.kind === "square") && node.parent) {
          node = node.parent;
        } else {
          node = new TextNode(node, char);
        }
        break;
      }
      case "text": {
        if (char === "\\" || char === "{") {
          node = node.parent;
          i--;
        } else if (char === "}" && node.parent.kind === "curly" || char === "]" && node.parent.kind === "square") {
          node = node.parent;
          i--;
        } else {
          node.text += char;
        }
        break;
      }
      case "command": {
        if (char === "{") {
          node = new BlockNode("curly", node);
        } else if (char === "[") {
          node = new BlockNode("square", node);
        } else if (char === "}" && node.parent.kind === "curly" || char === "]" && node.parent.kind === "square" || /\s/.test(char) || node.args.length > 0) {
          node = node.parent;
          i--;
        } else {
          node.command += char;
        }
      }
    }
  }
  return rootNode;
}
__name(parseLaTeX, "parseLaTeX");
function stringifyLaTeX(ast) {
  return stringifyBlock(ast);
}
__name(stringifyLaTeX, "stringifyLaTeX");
function stringifyBlock(block) {
  const content = block.children.map((node) => {
    switch (node.type) {
      case "block":
        return stringifyBlock(node);
      case "command":
        return stringifyCommand(node);
      case "text":
        return node.text;
    }
  }).join("");
  switch (block.kind) {
    case "root":
      return content;
    case "curly":
      return `{${content}}`;
    case "square":
      return `[${content}]`;
  }
}
__name(stringifyBlock, "stringifyBlock");
function stringifyCommand(node) {
  return `\\${node.command}${node.args.map(stringifyBlock).join("")}`;
}
__name(stringifyCommand, "stringifyCommand");

// src/transforms/encloseBraces.ts
function doubleEnclose(str) {
  const latex = parseLaTeX(str);
  const alreadyDoubleEnclosed = latex.children.length === 1 && latex.children[0]?.type === "block" && latex.children[0]?.kind === "curly" && latex.children[0].children.length === 1 && latex.children[0].children[0]?.type === "block" && latex.children[0].children[0]?.kind === "curly";
  const result = stringifyLaTeX(latex);
  return alreadyDoubleEnclosed ? result : `{${result}}`;
}
__name(doubleEnclose, "doubleEnclose");

// src/format.ts
function formatBibtex(ast) {
  const bibtex = ast.children.map((child) => formatNode(child)).join("").trimEnd();
  return `${bibtex}
`;
}
__name(formatBibtex, "formatBibtex");
function formatNode(child) {
  if (child.type === "text") {
    return `${child.whitespacePrefix}${child.text}`;
  }
  if (!child.block) throw new Error("FATAL!");
  switch (child.block.type) {
    case "preamble":
    case "string":
    case "comment":
      return `${child.whitespacePrefix}${child.block.raw}`;
    case "entry":
      return `${child.whitespacePrefix}${formatEntry(child.command, child.block)}`;
  }
}
__name(formatNode, "formatNode");
function formatEntry(entryType, entry) {
  let bibtex = `@${entryType}{`;
  if (entry.key) bibtex += `${entry.key},`;
  for (const field of entry.fields) {
    bibtex += `${field.whitespacePrefix}${field.name}`;
    const value = formatValue(field);
    if (value) {
      bibtex += `${field.value.whitespacePrefix}= ${value}`;
    }
    if (field.hasComma) bibtex += ",";
  }
  bibtex += "\n}";
  return bibtex;
}
__name(formatEntry, "formatEntry");
function formatValue(field) {
  return field.value.concat.map(({ type, value }) => {
    switch (type) {
      case "literal":
        return value;
      case "braced":
        return doubleEnclose(value);
      case "quoted":
        return `"${value}"`;
    }
  }).join(" # ");
}
__name(formatValue, "formatValue");

// src/ASTProxy.ts
var ASTProxy = class {
  constructor(ast) {
    this.fieldLookup = /* @__PURE__ */ new Map();
    this.renderValueLookup = /* @__PURE__ */ new Map();
    this.#ast = ast;
  }
  static {
    __name(this, "ASTProxy");
  }
  #ast;
  root() {
    return this.#ast;
  }
  fields() {
    return this.entries().flatMap((entry) => entry.fields);
  }
  entries() {
    return this.#ast.children.filter((node) => node.type === "block").map((block) => block.block).filter((entry) => entry?.type === "entry");
  }
  invalidateField(field) {
    this.renderValueLookup.delete(field);
  }
  lookupField(entry, fieldLc) {
    let fieldNode = this.fieldLookup.get(entry)?.get(fieldLc);
    if (fieldNode === void 0) {
      fieldNode = entry.fields.find(
        (field) => field.name.toLocaleLowerCase() === fieldLc
      );
    }
    return fieldNode;
  }
  lookupRenderedEntryValue(node, fieldName) {
    const field = node.type === "entry" ? this.lookupField(node, (fieldName ?? "").toLocaleLowerCase()) : node;
    if (!field) {
      return "";
    }
    let value = this.renderValueLookup.get(field);
    if (value === void 0) {
      const entryValue = formatValue(field) ?? "";
      value = parseLaTeX(entryValue).renderAsText();
      this.renderValueLookup.set(field, value);
    }
    return value;
  }
  lookupRenderedEntryValues(entry) {
    const values = /* @__PURE__ */ new Map();
    for (const field of entry.fields) {
      values.set(field.name, this.lookupRenderedEntryValue(field));
    }
    return values;
  }
};

// src/debug.ts
function logAST(node, depth = 0) {
  const indent = "  ".repeat(depth);
  let log = `
${indent}${node.type} ws="${"whitespacePrefix" in node ? node.whitespacePrefix.replace(/\n/g, "\\n") : ""}"`;
  switch (node.type) {
    case "root":
      for (const child of node.children) {
        log += logAST(child, depth + 1);
      }
      break;
    case "block":
      log += ` command="${node.command}"`;
      if (node.block) {
        log += logAST(node.block, depth + 1);
      }
      break;
    case "concat":
      for (const value of node.concat) {
        log += logAST(value, depth + 1);
      }
      break;
    case "entry":
      log += ` key="${node.key}"`;
      for (const field of node.fields) {
        log += logAST(field, depth + 1);
      }
      break;
    case "field":
      log += ` name="${node.name}"`;
      log += logAST(node.value, depth + 1);
      break;
    case "text":
      log += ` text="${node.text.replace(/\n/g, "\\n")}"`;
      break;
    case "braced":
    case "quoted":
    case "comment":
    case "preamble":
    case "string":
    case "literal":
      break;
  }
  return log;
}
__name(logAST, "logAST");

// src/optionDefinitions.ts
var DEFAULT_MERGE_CHECK = ["doi", "citation", "abstract"];
var DEFAULT_ALIGN = 0;
var DEFAULT_SPACE = 2;
var DEFAULT_WRAP = 80;
var DEFAULT_FIELD_SORT = [
  "title",
  "shorttitle",
  "author",
  "year",
  "month",
  "day",
  "journal",
  "booktitle",
  "location",
  "on",
  "publisher",
  "address",
  "series",
  "volume",
  "number",
  "pages",
  "doi",
  "isbn",
  "issn",
  "url",
  "urldate",
  "copyright",
  "category",
  "note",
  "metadata"
];
var DEFAULT_SORT = ["key"];
var DEFAULT_KEY_TEMPLATE = "[auth:required:lower][year:required][veryshorttitle:lower][duplicateNumber]";
var optionDefinitions = [
  {
    key: "help",
    cli: { "--help": true, "-h": true },
    title: "Help",
    description: ["Show help"],
    type: "boolean"
  },
  {
    key: "v2",
    cli: { "--v2": true },
    title: "Enable planned v2 CLI changes",
    description: [
      "Input files will no longer be modified by default. Instead, you will need to specify `--modify`/`-m` option to overwrite the file, or `--output`/`-o` to output to a different file."
    ],
    type: "string",
    defaultValue: void 0
  },
  {
    key: "outputPath",
    cli: { "--output": /* @__PURE__ */ __name((args) => args[0], "--output"), "-o": /* @__PURE__ */ __name((args) => args[0], "-o") },
    title: "Output path",
    description: [
      "Write output to specified path. When omitted (and -m/--modify is not used), the result will be printed to stdout."
    ],
    type: "string",
    defaultValue: void 0
  },
  {
    key: "modify",
    cli: { "--modify": true, "-m": true, "--no-modify": false },
    title: "Modify input files",
    description: [
      "Overwrite the original input files with the tidied result. This is enabled by default but will be disabled by default in v2. For v1, use --no-modify to output to stdout instead of overwriting the input files."
    ],
    type: "boolean",
    defaultValue: false
    // TODO: In v2, switch this to false
  },
  {
    key: "omit",
    cli: {
      "--omit": /* @__PURE__ */ __name((args) => {
        if (args.length === 0) {
          console.error("Expected a omit list");
          process.exit(1);
        }
        return args;
      }, "--omit")
    },
    toCLI: /* @__PURE__ */ __name((val) => Array.isArray(val) && val.length > 0 ? `--omit=${val.join(",")}` : void 0, "toCLI"),
    title: "Remove fields",
    description: ["Remove specified fields from bibliography entries."],
    examples: ["--omit=id,name"],
    type: "string[]",
    defaultValue: []
  },
  {
    key: "wikiConfig",
    cli: { "--wikiConfig": true, "--no-wikiConfig": false },
    toCLI: /* @__PURE__ */ __name((val) => val ? "--curly" : void 0, "toCLI"),
    title: "wikiConfig",
    description: [
      "wikiConfig"
    ],
    type: "boolean",
    defaultValue: true
  },
  {
    key: "curly",
    cli: { "--curly": true, "--no-curly": false },
    toCLI: /* @__PURE__ */ __name((val) => val ? "--curly" : void 0, "toCLI"),
    title: "Enclose values in braces",
    description: [
      'Enclose all property values in braces. Quoted values will be converted to braces. For example, "Journal of Tea" will become {Journal of Tea}.'
    ],
    type: "boolean",
    defaultValue: false
  },
  {
    key: "numeric",
    cli: { "--numeric": true, "--no-numeric": false },
    toCLI: /* @__PURE__ */ __name((val) => val ? "--numeric" : void 0, "toCLI"),
    title: "Use numeric values where possible",
    description: [
      "Strip quotes and braces from numeric/month values. For example, {1998} will become 1998."
    ],
    type: "boolean",
    defaultValue: false
  },
  {
    key: "months",
    cli: { "--months": true },
    toCLI: /* @__PURE__ */ __name((val) => val ? "--months" : void 0, "toCLI"),
    title: "Abbreviate months",
    description: [
      "Convert all months to three letter abbreviations (jan, feb, etc)."
    ],
    type: "boolean",
    defaultValue: false
  },
  {
    key: "space",
    cli: {
      "--space": /* @__PURE__ */ __name((args) => args.length > 0 ? Number(args[0]) : true, "--space")
    },
    toCLI: /* @__PURE__ */ __name((val, opt) => {
      if (opt.tab) return void 0;
      if (typeof val === "number" && val !== DEFAULT_SPACE)
        return `--space=${val}`;
      if (val && val !== DEFAULT_SPACE) return "--space";
      return void 0;
    }, "toCLI"),
    title: "Indent with spaces",
    description: [
      "Indent all fields with the specified number of spaces. Ignored if tab is set."
    ],
    examples: ["--space=2 (default)", "--space=4"],
    type: "boolean | number",
    convertBoolean: { true: DEFAULT_SPACE, false: void 0 },
    defaultValue: DEFAULT_SPACE
  },
  {
    key: "tab",
    cli: { "--tab": true, "--no-tab": false },
    toCLI: /* @__PURE__ */ __name((val) => val ? "--tab" : void 0, "toCLI"),
    title: "Indent with tabs",
    description: ["Indent all fields with a tab."],
    type: "boolean",
    defaultValue: false
  },
  {
    key: "align",
    cli: {
      "--align": /* @__PURE__ */ __name((args) => Number(args[0]), "--align"),
      "--no-align": false
    },
    toCLI: /* @__PURE__ */ __name((val) => {
      if (val === false || val === 1 || val === 0) return "--no-align";
      if (typeof val === "number" && val !== DEFAULT_ALIGN)
        return `--align=${val}`;
      return void 0;
    }, "toCLI"),
    title: "Align values",
    description: [
      "Insert whitespace between fields and values so that values are visually aligned."
    ],
    examples: ["--align=14 (default)"],
    type: "boolean | number",
    convertBoolean: { true: DEFAULT_ALIGN, false: 1 },
    defaultValue: DEFAULT_ALIGN
  },
  {
    key: "blankLines",
    cli: { "--blank-lines": true, "--no-blank-lines": false },
    toCLI: /* @__PURE__ */ __name((val) => val ? "--blank-lines" : void 0, "toCLI"),
    title: "Insert blank lines",
    description: ["Insert an empty line between each entry."],
    type: "boolean"
  },
  {
    key: "sort",
    cli: {
      "--sort": /* @__PURE__ */ __name((args) => args.length > 0 ? args : true, "--sort"),
      "--no-sort": false
    },
    toCLI: /* @__PURE__ */ __name((val) => {
      if (Array.isArray(val) && val.length > 0)
        return `--sort=${val.join(",")}`;
      if (val === true) return "--sort";
      return void 0;
    }, "toCLI"),
    title: "Sort bibliography entries",
    description: [
      "Sort entries by the specified field names (citation key is used if no fields are specified). For descending order, prefix the field with a dash (-).",
      "Multiple fields may be specified to sort everything by first field, then by the second field whenever the first field for entries are equal, etc.",
      "The following additional fields are also permitted: key (entry citation key), type (sorts by the type of entry, e.g. article), and special (ensures that @string, @preamble, @set, and @xdata entries are first). "
    ],
    examples: [
      "--sort (sort by citation key)",
      "--sort=-year,name (sort year descending then name ascending)",
      "--sort=name,year"
    ],
    type: "boolean | string[]",
    convertBoolean: { true: DEFAULT_SORT, false: void 0 }
  },
  {
    key: "duplicates",
    cli: {
      "--duplicates": /* @__PURE__ */ __name((args) => {
        if (args.length === 0) return true;
        for (const i of args) {
          if (i !== "doi" && i !== "key" && i !== "abstract" && i !== "citation") {
            console.error(`Invalid key for merge option: "${i}"`);
            process.exit(1);
          }
        }
        return args;
      }, "--duplicates")
    },
    toCLI: /* @__PURE__ */ __name((val) => {
      if (Array.isArray(val) && val.length > 0)
        return `--duplicates=${val.join(",")}`;
      if (val === true) return "--duplicates";
      return void 0;
    }, "toCLI"),
    title: "Check for duplicates",
    description: [
      "Warn if duplicates are found, which are entries where DOI, abstract, or author and title are the same."
    ],
    examples: [
      "--duplicates doi (same DOIs)",
      "--duplicates key (same IDs)",
      "--duplicates abstract (similar abstracts)",
      "--duplicates citation (similar author and titles)",
      "--duplicates doi, key (identical DOI or keys)",
      "--duplicates (same DOI, key, abstract, or citation)"
    ],
    type: "boolean | ('doi' | 'key' | 'abstract' | 'citation')[]",
    convertBoolean: { true: DEFAULT_MERGE_CHECK, false: void 0 },
    defaultValue: /* @__PURE__ */ __name((options) => options.merge ? DEFAULT_MERGE_CHECK : void 0, "defaultValue")
  },
  {
    key: "merge",
    cli: {
      "--merge": /* @__PURE__ */ __name((args) => {
        if (args.length === 0) return true;
        if (args[0] !== "first" && args[0] !== "last" && args[0] !== "combine" && args[0] !== "overwrite") {
          console.error(`Invalid merge strategy: "${args[0]}"`);
          process.exit(1);
        }
        return args[0];
      }, "--merge"),
      "--no-merge": false
    },
    toCLI: /* @__PURE__ */ __name((val) => {
      if (typeof val === "string") return `--merge=${val}`;
      if (val) return "--merge";
      return void 0;
    }, "toCLI"),
    title: "Merge duplicate entries",
    description: [
      "Merge duplicates entries. Use the duplicates option to determine how duplicates are identified. There are different ways to merge:",
      "- first: only keep the original entry",
      "- last: only keep the last found duplicate",
      "- combine: keep original entry and merge in fields of duplicates if they do not already exist",
      "- overwrite: keep original entry and merge in fields of duplicates, overwriting existing fields if they exist"
    ],
    type: "boolean | 'first' | 'last' | 'combine' | 'overwrite'",
    convertBoolean: { true: "combine", false: void 0 }
  },
  {
    key: "stripEnclosingBraces",
    cli: { "--strip-enclosing-braces": true },
    toCLI: /* @__PURE__ */ __name((val) => val ? "--strip-enclosing-braces" : void 0, "toCLI"),
    title: "Strip double-braced values",
    description: [
      "Where an entire value is enclosed in double braces, remove the extra braces. For example, {{Journal of Tea}} will become {Journal of Tea}."
    ],
    type: "boolean",
    defaultValue: false
  },
  {
    key: "dropAllCaps",
    cli: { "--drop-all-caps": true },
    toCLI: /* @__PURE__ */ __name((val) => val ? "--drop-all-caps" : void 0, "toCLI"),
    title: "Drop all caps",
    description: [
      "Where values are all caps, make them title case. For example, {JOURNAL OF TEA} will become {Journal of Tea}. Roman numerals will be left unchanged."
    ],
    type: "boolean",
    defaultValue: false
  },
  {
    key: "escape",
    cli: { "--escape": true, "--no-escape": false },
    toCLI: /* @__PURE__ */ __name((val) => val === false ? "--no-escape" : void 0, "toCLI"),
    title: "Escape special characters",
    description: [
      "Escape special characters, such as umlaut. This ensures correct typesetting with latex. Enabled by default."
    ],
    type: "boolean",
    defaultValue: false
  },
  {
    key: "sortFields",
    cli: { "--sort-fields": /* @__PURE__ */ __name((args) => args.length > 0 ? args : true, "--sort-fields") },
    toCLI: /* @__PURE__ */ __name((val) => {
      if (Array.isArray(val) && val.length > 0) {
        if (JSON.stringify(val) === JSON.stringify(DEFAULT_FIELD_SORT)) {
          return "--sort-fields";
        }
        return `--sort-fields=${val.join(",")}`;
      }
      if (val === true) return "--sort-fields";
      return void 0;
    }, "toCLI"),
    title: "Sort fields",
    description: [
      "Sort the fields within entries.",
      "If no fields are specified fields will be sorted by: title, shorttitle, author, year, month, day, journal, booktitle, location, on, publisher, address, series, volume, number, pages, doi, isbn, issn, url, urldate, copyright, category, note, metadata"
    ],
    examples: ["--sort-fields=name,author"],
    type: "boolean | string[]",
    convertBoolean: { true: DEFAULT_FIELD_SORT, false: void 0 },
    defaultValue: void 0
  },
  {
    key: "sortProperties",
    cli: { "--sort-properties": /* @__PURE__ */ __name((args) => args.length > 0 ? args : true, "--sort-properties") },
    title: "Sort properties",
    description: ["Alias of sort fields (legacy)"],
    type: "boolean | string[]",
    deprecated: true
  },
  {
    key: "stripComments",
    cli: { "--strip-comments": true, "--no-strip-comments": false },
    toCLI: /* @__PURE__ */ __name((val) => val ? "--strip-comments" : void 0, "toCLI"),
    title: "Remove comments",
    description: ["Remove all comments from the bibtex source."],
    type: "boolean",
    defaultValue: false
  },
  {
    key: "trailingCommas",
    cli: { "--trailing-commas": true, "--no-trailing-commas": true },
    toCLI: /* @__PURE__ */ __name((val) => val ? "--trailing-commas" : void 0, "toCLI"),
    title: "Trailing commas",
    description: ["End the last key value pair in each entry with a comma."],
    type: "boolean",
    defaultValue: false
  },
  {
    key: "encodeUrls",
    cli: { "--encode-urls": true, "--no-encode-urls": true },
    toCLI: /* @__PURE__ */ __name((val) => val ? "--encode-urls" : void 0, "toCLI"),
    title: "Encode URLs",
    description: [
      "Replace invalid URL characters with percent encoded values."
    ],
    type: "boolean",
    defaultValue: false
  },
  {
    key: "tidyComments",
    cli: { "--tidy-comments": true, "--no-tidy-comments": false },
    toCLI: /* @__PURE__ */ __name((val) => val === false ? "--no-tidy-comments" : void 0, "toCLI"),
    title: "Tidy comments",
    description: ["Remove whitespace surrounding comments."],
    type: "boolean",
    defaultValue: false
  },
  {
    key: "removeEmptyFields",
    cli: { "--remove-empty-fields": true, "--no-remove-empty-fields": false },
    toCLI: /* @__PURE__ */ __name((val) => val ? "--remove-empty-fields" : void 0, "toCLI"),
    title: "Remove empty fields",
    description: ["Remove any fields that have empty values."],
    type: "boolean",
    defaultValue: false
  },
  {
    key: "removeDuplicateFields",
    cli: {
      "--remove-dupe-fields": true,
      "--no-remove-dupe-fields": false
    },
    toCLI: /* @__PURE__ */ __name((val) => val === false ? "--no-remove-dupe-fields" : void 0, "toCLI"),
    title: "Remove duplicate fields",
    description: [
      "Only allow one of each field in each entry. Enabled by default."
    ],
    type: "boolean",
    defaultValue: false
  },
  {
    key: "generateKeys",
    cli: { "--generate-keys": /* @__PURE__ */ __name((args) => args.length > 0 ? args : true, "--generate-keys") },
    toCLI: /* @__PURE__ */ __name((val) => {
      if (val === true || val === DEFAULT_KEY_TEMPLATE)
        return "--generate-keys";
      if (typeof val === "string")
        return `--generate-keys="${val.replace(/"/g, '\\"')}"`;
      return void 0;
    }, "toCLI"),
    title: "Generate citation keys [Experimental]",
    description: [
      "For all entries replace the key with a new key of the form <author><year><title>. A JabRef citation pattern can be provided. This is an experimental option that may change without warning."
    ],
    type: "boolean | string",
    convertBoolean: {
      true: DEFAULT_KEY_TEMPLATE,
      false: void 0
    },
    defaultValue: true
  },
  {
    key: "maxAuthors",
    cli: { "--max-authors": /* @__PURE__ */ __name((args) => Number(args[0]), "--max-authors") },
    toCLI: /* @__PURE__ */ __name((val) => val ? `--max-authors=${val}` : void 0, "toCLI"),
    title: "Maximum authors",
    description: [
      'Truncate authors if above a given number into "and others".'
    ],
    type: "number"
  },
  {
    key: "lowercase",
    cli: { "--no-lowercase": false },
    toCLI: /* @__PURE__ */ __name((val) => val === false ? "--no-lowercase" : void 0, "toCLI"),
    title: "Lowercase fields",
    description: ["Lowercase field names and entry type. Enabled by default."],
    type: "boolean",
    defaultValue: false
  },
  {
    key: "enclosingBraces",
    cli: {
      "--enclosing-braces": /* @__PURE__ */ __name((args) => args.length > 0 ? args : true, "--enclosing-braces")
    },
    toCLI: /* @__PURE__ */ __name((val) => {
      if (Array.isArray(val) && val.length > 0)
        return `--enclosing-braces=${val.join(",")}`;
      if (val === true) return "--enclosing-braces";
      return void 0;
    }, "toCLI"),
    title: "Enclose values in double braces",
    description: [
      "Enclose the given fields in double braces, such that case is preserved during BibTeX compilation."
    ],
    examples: [
      "--enclosing-braces=title,journal (output title and journal fields will be of the form {{This is a title}})",
      "--enclosing-braces (equivalent to ---enclosing-braces=title)"
    ],
    type: "boolean | string[]",
    convertBoolean: { true: ["title"], false: void 0 }
  },
  {
    key: "removeBraces",
    cli: {
      "--remove-braces": /* @__PURE__ */ __name((args) => args.length > 0 ? args : true, "--remove-braces")
    },
    toCLI: /* @__PURE__ */ __name((val) => {
      if (Array.isArray(val) && val.length > 0)
        return `--remove-braces=${val.join(",")}`;
      if (val === true) return "--remove-braces";
      return void 0;
    }, "toCLI"),
    title: "Remove braces",
    description: [
      "Remove any curly braces within the value, unless they are part of a command."
    ],
    examples: [
      "--remove-braces=title,journal",
      "--remove-braces (equivalent to ---remove-braces=title)"
    ],
    type: "boolean | string[]",
    convertBoolean: { true: ["title"], false: void 0 }
  },
  {
    key: "wrap",
    cli: {
      "--wrap": /* @__PURE__ */ __name((args) => args.length > 0 ? Number(args[0]) : true, "--wrap"),
      "--no-wrap": false
    },
    toCLI: /* @__PURE__ */ __name((val) => val ? `--wrap=${val}` : void 0, "toCLI"),
    title: "Wrap values",
    description: ["Wrap long values at the given column"],
    examples: ["--wrap (80 by default)", "--wrap=82"],
    type: "boolean | number",
    convertBoolean: { true: DEFAULT_WRAP, false: void 0 }
  },
  {
    key: "version",
    cli: { "--version": true, "-v": true },
    title: "Version",
    description: ["Show bibtex-tidy version."],
    type: "boolean"
  },
  {
    key: "quiet",
    cli: { "--quiet": true },
    title: "Quiet",
    description: ["Suppress logs on stdout."],
    type: "boolean"
  },
  {
    key: "backup",
    cli: { "--backup": true, "--no-backup": false },
    title: "Backup",
    description: [
      "Make a backup <filename>.original. Enabled by default (unless --modify is explicitly provided or outputting to a different file/stdio). Deprecated but provided for backward compatibility."
    ],
    type: "boolean",
    defaultValue: false,
    deprecated: true
  }
];

// src/optionUtils.ts
function normalizeOptions(options) {
  return Object.fromEntries(
    optionDefinitions.map((def) => {
      const key = def.key;
      const value = options[key];
      if (def.convertBoolean && typeof value === "boolean") {
        return [
          key,
          value ? def.convertBoolean.true : def.convertBoolean.false
        ];
      }
      if (typeof value === "undefined" && def.defaultValue !== void 0) {
        if (typeof def.defaultValue === "function") {
          return [key, def.defaultValue(options)];
        }
        return [key, def.defaultValue];
      }
      return [key, value];
    })
  );
}
__name(normalizeOptions, "normalizeOptions");

// src/parsers/bibtexParser.ts
var RootNode = class {
  constructor(children = []) {
    this.type = "root";
    this.children = children;
  }
  static {
    __name(this, "RootNode");
  }
};
var TextNode2 = class {
  constructor(parent, text, whitespacePrefix) {
    this.type = "text";
    this.parent = parent;
    this.text = text;
    this.whitespacePrefix = whitespacePrefix;
    parent.children.push(this);
  }
  static {
    __name(this, "TextNode");
  }
};
var BlockNode2 = class {
  constructor(parent, whitespacePrefix) {
    this.type = "block";
    this.command = "";
    this.parent = parent;
    this.whitespacePrefix = whitespacePrefix;
    parent.children.push(this);
  }
  static {
    __name(this, "BlockNode");
  }
};
var CommentNode = class {
  constructor(parent, raw, braces, parens) {
    this.type = "comment";
    this.parent = parent;
    this.raw = raw;
    this.braces = braces;
    this.parens = parens;
    parent.block = this;
  }
  static {
    __name(this, "CommentNode");
  }
};
var PreambleNode = class {
  constructor(parent, raw, braces, parens) {
    this.type = "preamble";
    this.parent = parent;
    this.raw = raw;
    this.braces = braces;
    this.parens = parens;
    parent.block = this;
  }
  static {
    __name(this, "PreambleNode");
  }
};
var StringNode = class {
  constructor(parent, raw, braces, parens) {
    this.type = "string";
    this.parent = parent;
    this.raw = raw;
    this.braces = braces;
    this.parens = parens;
    parent.block = this;
  }
  static {
    __name(this, "StringNode");
  }
};
var EntryNode = class {
  constructor(parent, wrapType) {
    this.type = "entry";
    this.parent = parent;
    this.wrapType = wrapType;
    parent.block = this;
    this.fields = [];
  }
  static {
    __name(this, "EntryNode");
  }
};
var FieldNode = class {
  constructor(parent, name = "", whitespacePrefix = "") {
    this.type = "field";
    this.hasComma = false;
    this.parent = parent;
    this.name = name;
    this.whitespacePrefix = whitespacePrefix;
    this.value = new ConcatNode(this);
  }
  static {
    __name(this, "FieldNode");
  }
};
var ConcatNode = class {
  constructor(parent) {
    this.type = "concat";
    this.canConsumeValue = true;
    this.whitespacePrefix = "";
    this.parent = parent;
    this.concat = [];
  }
  static {
    __name(this, "ConcatNode");
  }
};
var LiteralNode = class {
  constructor(parent, value) {
    this.type = "literal";
    this.parent = parent;
    this.value = value;
  }
  static {
    __name(this, "LiteralNode");
  }
};
function createLiteralNode(parent, value) {
  const node = new LiteralNode(parent, value);
  parent.concat.push(node);
  return node;
}
__name(createLiteralNode, "createLiteralNode");
var BracedNode = class {
  constructor(parent) {
    this.type = "braced";
    this.value = "";
    /** Used to count opening and closing braces */
    this.depth = 0;
    this.parent = parent;
  }
  static {
    __name(this, "BracedNode");
  }
};
function createBracedNode(parent) {
  const node = new BracedNode(parent);
  parent.concat.push(node);
  return node;
}
__name(createBracedNode, "createBracedNode");
var QuotedNode = class {
  constructor(parent) {
    this.type = "quoted";
    this.value = "";
    /** Used to count opening and closing braces */
    this.depth = 0;
    this.parent = parent;
  }
  static {
    __name(this, "QuotedNode");
  }
};
function createQuotedNode(parent) {
  const node = new QuotedNode(parent);
  parent.concat.push(node);
  return node;
}
__name(createQuotedNode, "createQuotedNode");
function parseBibTeX(input) {
  const rootNode = new RootNode();
  let node = rootNode;
  let line = 1;
  let column = 0;
  let whitespace = "";
  const flushWhitespace = /* @__PURE__ */ __name(() => {
    const ws = whitespace;
    whitespace = "";
    return ws;
  }, "flushWhitespace");
  for (let i = 0; i < input.length; i++) {
    const char = input[i] ?? "";
    const prev = input[i - 1] ?? "";
    if (char === "\n") {
      line++;
      column = 0;
    }
    column++;
    switch (node.type) {
      case "root": {
        if (char === "@") {
          node = new BlockNode2(node, flushWhitespace());
        } else if (isWhitespace(char)) {
          whitespace += char;
        } else {
          node = new TextNode2(node, char, flushWhitespace());
        }
        break;
      }
      case "text": {
        if (char === "@" && /[\s\r\n}]/.test(prev)) {
          node = new BlockNode2(node.parent, "");
        } else {
          node.text += char;
        }
        break;
      }
      case "block": {
        if (char === "@") {
          const prevNode = node.parent.children[node.parent.children.length - 2];
          if (prevNode?.type === "text") {
            prevNode.text += `@${node.command}`;
          } else {
            node.parent.children.pop();
            new TextNode2(
              node.parent,
              `@${node.command}`,
              node.whitespacePrefix
            );
            node.parent.children.push(node);
          }
          node.command = "";
        } else if (char === "{" || char === "(") {
          const commandTrimmed = node.command.trim();
          if (commandTrimmed === "" || /\s/.test(commandTrimmed)) {
            node.parent.children.pop();
            node = new TextNode2(
              node.parent,
              `@${node.command}${char}`,
              node.whitespacePrefix
            );
          } else {
            node.command = commandTrimmed;
            const command = node.command.toLowerCase();
            const [braces, parens] = char === "{" ? [1, 0] : [0, 1];
            const raw = `@${command}${char}`;
            switch (command) {
              case "string":
                node = new StringNode(node, raw, braces, parens);
                break;
              case "preamble":
                node = new PreambleNode(node, raw, braces, parens);
                break;
              case "comment":
                node = new CommentNode(node, raw, braces, parens);
                break;
              default:
                node = new EntryNode(node, char);
                break;
            }
          }
        } else if (char.match(/[=#,})[\]]/)) {
          node.parent.children.pop();
          node = new TextNode2(
            node.parent,
            `@${node.command}${char}`,
            flushWhitespace()
          );
        } else {
          node.command += char;
        }
        break;
      }
      case "comment":
      case "string":
      case "preamble":
        if (char === "{") {
          node.braces++;
        } else if (char === "}") {
          node.braces--;
        } else if (char === "(") {
          node.parens++;
        } else if (char === ")") {
          node.parens--;
        }
        node.raw += char;
        if (node.braces === 0 && node.parens === 0) {
          node = node.parent.parent;
        }
        break;
      case "entry": {
        if (isWhitespace(char)) {
          if (!node.key) {
          } else {
            node.keyEnded = true;
          }
        } else if (char === ",") {
          node = new FieldNode(node);
        } else if (node.wrapType === "{" && char === "}" || node.wrapType === "(" && char === ")") {
          node = node.parent.parent;
        } else if (char === "=" && node.key && isValidFieldName(node.key)) {
          const field = new FieldNode(node, node.key);
          node.fields.push(field);
          node.key = void 0;
          node = field.value;
        } else if (node.keyEnded) {
          throw new BibTeXSyntaxError(
            input,
            node,
            i,
            line,
            column,
            "The entry key cannot contain whitespace"
          );
        } else if (!isValidKeyCharacter(char)) {
          throw new BibTeXSyntaxError(
            input,
            node,
            i,
            line,
            column,
            `The entry key cannot contain the character (${char})`
          );
        } else {
          node.key = (node.key ?? "") + char;
        }
        break;
      }
      case "field": {
        if (char === "}" || char === ")") {
          node.name = node.name.trim();
          node = node.parent.parent.parent;
        } else if (char === "=") {
          node.name = node.name.trim();
          node = node.value;
        } else if (char === ",") {
          node.name = node.name.trim();
          node = new FieldNode(node.parent);
        } else if (!isValidFieldName(char)) {
          throw new BibTeXSyntaxError(input, node, i, line, column);
        } else if (!node.name) {
          if (!isWhitespace(char)) {
            node.parent.fields.push(node);
            node.name = char;
          } else {
            node.whitespacePrefix += char;
          }
        } else {
          node.name += char;
        }
        break;
      }
      case "concat": {
        if (isWhitespace(char)) {
          break;
        }
        if (node.canConsumeValue) {
          if (/[#=,}()[\]]/.test(char)) {
            throw new BibTeXSyntaxError(input, node, i, line, column);
          }
          node.canConsumeValue = false;
          if (char === "{") {
            node = createBracedNode(node);
          } else if (char === '"') {
            node = createQuotedNode(node);
          } else {
            node = createLiteralNode(node, char);
          }
        } else {
          if (char === ",") {
            node = new FieldNode(node.parent.parent);
          } else if (char === "}" || char === ")") {
            node = node.parent.parent.parent.parent;
          } else if (char === "#") {
            node.canConsumeValue = true;
          } else {
            throw new BibTeXSyntaxError(input, node, i, line, column);
          }
        }
        break;
      }
      case "literal":
        if (isWhitespace(char)) {
          node = node.parent;
        } else if (char === ",") {
          node = new FieldNode(node.parent.parent.parent);
        } else if (char === "}") {
          node = node.parent.parent.parent.parent.parent;
        } else if (char === "#") {
          node = node.parent;
          node.canConsumeValue = true;
        } else {
          node.value += char;
        }
        break;
      // Values may be enclosed in curly braces. Curly braces may be used within
      // the value but they must be balanced.
      case "braced":
        if (char === "}" && node.depth === 0) {
          node = node.parent;
          break;
        }
        if (char === "{") {
          node.depth++;
        } else if (char === "}") {
          node.depth--;
        }
        node.value += char;
        break;
      // Values may be enclosed in double quotes. Curly braces may be used
      // within quoted values but they must be balanced.
      //
      // To escape a double quote, surround it with braces `{"}`.
      // https://web.archive.org/web/20210422110817/https://maverick.inria.fr/~Xavier.Decoret/resources/xdkbibtex/bibtex_summary.html
      case "quoted":
        if (char === '"' && node.depth === 0) {
          node = node.parent;
          break;
        }
        if (char === "{") {
          node.depth++;
        } else if (char === "}") {
          node.depth--;
          if (node.depth < 0) {
            throw new BibTeXSyntaxError(input, node, i, line, column);
          }
        }
        node.value += char;
        break;
    }
  }
  return rootNode;
}
__name(parseBibTeX, "parseBibTeX");
function isWhitespace(string) {
  return /^\s*$/.test(string);
}
__name(isWhitespace, "isWhitespace");
function isValidKeyCharacter(char) {
  return !/[#%{}~$,]/.test(char);
}
__name(isValidKeyCharacter, "isValidKeyCharacter");
function isValidFieldName(char) {
  return !/[=,{}()[\]]/.test(char);
}
__name(isValidFieldName, "isValidFieldName");
var BibTeXSyntaxError = class extends Error {
  static {
    __name(this, "BibTeXSyntaxError");
  }
  constructor(input, node, pos, line, column, hint) {
    super(
      `Line ${line}:${column}: Syntax Error in ${node.type} (${hint})
${input.slice(Math.max(0, pos - 20), pos)}>>${input[pos]}<<${input.slice(pos + 1, pos + 20)}`
    );
    this.name = "Syntax Error";
    this.char = input[pos] ?? "";
    this.pos = pos;
    this.line = line;
    this.column = column;
    this.hint = hint;
  }
};

// src/transforms/abbreviateMonths.ts
var monthAliases = {
  jan: ["1", "jan", "january"],
  feb: ["2", "feb", "february"],
  mar: ["3", "mar", "march"],
  apr: ["4", "apr", "may"],
  may: ["5", "may", "april"],
  jun: ["6", "jun", "june"],
  jul: ["7", "jul", "july"],
  aug: ["8", "aug", "august"],
  sep: ["9", "sep", "september"],
  oct: ["10", "oct", "october"],
  nov: ["11", "nov", "november"],
  dec: ["12", "dec", "december"]
};
function createAbbreviateMonthsTransform() {
  const months = new Map(
    Object.entries(monthAliases).flatMap(
      ([abbr, aliases]) => aliases.map((alias) => [alias, abbr])
    )
  );
  return {
    name: "abbreviate-months",
    apply: /* @__PURE__ */ __name((astProxy) => {
      for (const field of astProxy.fields()) {
        if (field.name.toLowerCase() === "month") {
          abbreviateMonthInField(astProxy, field, months);
        }
      }
      return void 0;
    }, "apply")
  };
}
__name(createAbbreviateMonthsTransform, "createAbbreviateMonthsTransform");
function abbreviateMonthInField(astProxy, field, months) {
  field.value.concat = field.value.concat.map((node) => {
    const abbr = abbreviateMonth(node.value, months);
    return abbr ? new LiteralNode(node.parent, abbr) : node;
  });
  astProxy.invalidateField(field);
}
__name(abbreviateMonthInField, "abbreviateMonthInField");
function abbreviateMonth(month, months) {
  return months.get(month.toLowerCase());
}
__name(abbreviateMonth, "abbreviateMonth");

// src/transforms/alignValues.ts
function createAlignValuesTransform(column) {
  return {
    name: "align-values",
    apply: /* @__PURE__ */ __name((astProxy) => {
      const fields = astProxy.fields();
      for (const field of fields) {
        const gap = Math.max(column - field.name.length, 1);
        field.value.whitespacePrefix = " ".repeat(gap);
      }
      return void 0;
    }, "apply")
  };
}
__name(createAlignValuesTransform, "createAlignValuesTransform");

// src/transforms/blankLines.ts
function createBlankLinesTransform() {
  return {
    name: "blank-lines",
    apply: /* @__PURE__ */ __name((astProxy) => {
      const children = astProxy.root().children;
      let prev;
      for (const child of children) {
        if (prev && !isComment(prev)) {
          child.whitespacePrefix = "\n\n";
        }
        prev = child;
      }
      return void 0;
    }, "apply")
  };
}
__name(createBlankLinesTransform, "createBlankLinesTransform");
function isComment(node) {
  return node.type === "text" || node.block?.type === "comment";
}
__name(isComment, "isComment");

// src/transforms/dropAllCaps.ts
function createDropAllCapsTransform() {
  return {
    name: "drop-all-caps",
    apply: /* @__PURE__ */ __name((astProxy) => {
      for (const field of astProxy.fields()) {
        dropAllCapsInField(astProxy, field);
      }
      return void 0;
    }, "apply")
  };
}
__name(createDropAllCapsTransform, "createDropAllCapsTransform");
function dropAllCapsInField(astProxy, field) {
  if (!astProxy.lookupRenderedEntryValue(field).match(/[a-z]/)) {
    console.log(astProxy.lookupRenderedEntryValue(field));
    for (const node of field.value.concat) {
      node.value = titleCase(node.value);
    }
    astProxy.invalidateField(field);
  }
}
__name(dropAllCapsInField, "dropAllCapsInField");
function titleCase(str) {
  return str.replace(/(\w)(\S*)/g, (_, first, rest) => {
    const word = first + rest;
    if (isRomanNumeral(word)) return word;
    return first.toLocaleUpperCase() + rest.toLocaleLowerCase();
  });
}
__name(titleCase, "titleCase");
function isRomanNumeral(str) {
  return /^M{0,4}(CM|CD|D?C{0,3})(XC|XL|L?X{0,3})(IX|IV|V?I{0,3})$/.test(str);
}
__name(isRomanNumeral, "isRomanNumeral");

// src/transforms/fieldCommas.ts
function createFieldCommasTransform(trailing) {
  return {
    name: "field-commas",
    apply: /* @__PURE__ */ __name((astProxy) => {
      const entries = astProxy.entries();
      for (const entry of entries) {
        for (let i = 0; i < entry.fields.length; i++) {
          const field = entry.fields[i];
          field.hasComma = i < entry.fields.length - 1 || trailing;
        }
      }
      return void 0;
    }, "apply")
  };
}
__name(createFieldCommasTransform, "createFieldCommasTransform");

// src/parsers/entryKeyTemplateParser.ts
function parseEntryKeyTemplate(template) {
  const tokens = [];
  const matches = template.matchAll(/\[[^:\]]+(?::[^:\]]+)*\]/g);
  let pos = 0;
  for (const match of matches) {
    if (match.index === void 0) break;
    if (match.index !== pos) {
      tokens.push(template.slice(pos, match.index));
    }
    const [tokenKeyN, ...modifierKeys] = match[0].slice(1, -1).split(":");
    if (!tokenKeyN) {
      throw new Error("Token parse error");
    }
    let n;
    const tokenKey = tokenKeyN.replace(/[0-9]+/g, (m) => {
      n = Number(m);
      return "N";
    });
    tokens.push({
      marker: tokenKey,
      parameter: n,
      modifiers: modifierKeys
    });
    pos = match.index + match[0].length;
  }
  if (pos < template.length) {
    tokens.push(template.slice(pos));
  }
  return tokens;
}
__name(parseEntryKeyTemplate, "parseEntryKeyTemplate");

// src/parsers/nameFieldParser.ts
function parseNameList(value) {
  return value.split(/\s+and\s+/i).map(parseName);
}
__name(parseNameList, "parseNameList");
function detectNameSyntax(tokens) {
  const names = tokens.filter((token) => token.type === "name");
  const prefixes = tokens.filter((token) => token.type === "prefix");
  const commas = tokens.filter((token) => token.type === "comma");
  if (tokens.length === 0) {
    return "Empty";
  }
  if (tokens.length === 1 && nameStr(tokens) === "others") {
    return "Others";
  }
  if (tokens.length === names.length && tokens.length === 1) {
    return "LastName";
  }
  if (tokens.length === names.length) {
    return "FirstName LastNames";
  }
  if (prefixes.length > 0 && commas.length === 0) {
    return "FirstNames Prefixes LastNames";
  }
  if (commas.length === 1) {
    return "LastNames, FirstNames Prefixes";
  }
  if (commas.length === 2) {
    return "LastNames, Suffixes, FirstNames Prefixes";
  }
  throw new Error(
    `Invalid name syntax: ${tokens.map((token) => token.type).join(" ")}`
  );
}
__name(detectNameSyntax, "detectNameSyntax");
function parseName(name) {
  const tokens = tokeniseName(name);
  switch (detectNameSyntax(tokens)) {
    case "Empty":
      return { first: "", last: "", pre: "", suf: "" };
    case "Others":
      return { first: "", last: "others", pre: "", suf: "" };
    case "LastName":
      return { first: "", last: nameStr(tokens), pre: "", suf: "" };
    case "FirstName LastNames": {
      const [first, last] = partition(tokens, ["name", "name"]);
      return { first: nameStr(first), last: nameStr(last), pre: "", suf: "" };
    }
    case "FirstNames Prefixes LastNames": {
      const [first, pre, last] = partition(tokens, [
        "name",
        "prefix",
        "name"
      ]);
      return {
        first: nameStr(first),
        pre: nameStr(pre),
        last: nameStr(last),
        suf: ""
      };
    }
    case "LastNames, FirstNames Prefixes": {
      const [lastNames, firstNames, prefixes] = partition(tokens, [
        "name",
        "comma",
        "prefix"
      ]);
      return {
        last: nameStr(lastNames),
        first: nameStr(firstNames),
        pre: nameStr(prefixes),
        suf: ""
      };
    }
    case "LastNames, Suffixes, FirstNames Prefixes": {
      const [lastNames, suffixes, firstNames, prefixes] = partition(tokens, [
        "name",
        "comma",
        "comma",
        "prefix"
      ]);
      return {
        last: nameStr(lastNames),
        suf: nameStr(suffixes),
        first: nameStr(firstNames),
        pre: nameStr(prefixes)
      };
    }
  }
}
__name(parseName, "parseName");
function tokeniseName(name) {
  const tokens = [];
  let current = "";
  function flushToken() {
    if (!current) return;
    tokens.push({
      type: isPrefixToken(current) ? "prefix" : "name",
      value: current
    });
  }
  __name(flushToken, "flushToken");
  for (const c of name) {
    if (c === ",") {
      flushToken();
      tokens.push({ type: "comma" });
      current = "";
    } else if (/\s/.test(c)) {
      flushToken();
      current = "";
    } else {
      current += c;
    }
  }
  flushToken();
  return tokens;
}
__name(tokeniseName, "tokeniseName");
function nameStr(tokens) {
  return tokens.filter(
    (token) => token.type !== "comma"
  ).map((token) => token.value).join(" ");
}
__name(nameStr, "nameStr");
function isPrefixToken(token) {
  return /^[a-z]/.test(token);
}
__name(isPrefixToken, "isPrefixToken");
function partition(tokens, divideBefore) {
  const partitions = divideBefore.map(() => []);
  let currPartition = -1;
  for (const token of tokens) {
    if (divideBefore[currPartition + 1] === token.type) {
      currPartition++;
    }
    partitions[currPartition]?.push(token);
  }
  return partitions;
}
__name(partition, "partition");

// src/generateKeys.ts
var SPECIAL_MARKERS = {
  auth: {
    description: "Last name of first authors",
    callback: /* @__PURE__ */ __name((v) => {
      const authors = parseNameList(v.get("author") ?? "");
      const author = authors[0]?.last;
      return author ? [author] : [];
    }, "callback")
  },
  authEtAl: {
    description: "If 1 or 2 authors, both authors, otherwise first author and EtAl",
    callback: /* @__PURE__ */ __name((v) => {
      const authors = parseNameList(v.get("author") ?? "");
      return [
        ...authors.slice(0, 2).map((author) => author.last),
        ...authors.length > 2 ? ["Et", "Al"] : []
      ];
    }, "callback")
  },
  authors: {
    description: "Last name all authors",
    callback: /* @__PURE__ */ __name((v) => {
      const authors = parseNameList(v.get("author") ?? "");
      return authors.map((author) => author.last);
    }, "callback")
  },
  authorsN: {
    description: "Last name N authors, with EtAl if more",
    callback: /* @__PURE__ */ __name((v, n = 0) => {
      const authors = parseNameList(v.get("author") ?? "");
      return [
        ...authors.slice(0, n).map((author) => author.last),
        ...authors.length > n ? ["Et", "Al"] : []
      ];
    }, "callback")
  },
  veryshorttitle: {
    description: "First non-function word of the title",
    callback: /* @__PURE__ */ __name((v) => nonFunctionWords(title(v)).slice(0, 1), "callback")
  },
  shorttitle: {
    description: "First three non-function words of the title",
    callback: /* @__PURE__ */ __name((v) => nonFunctionWords(title(v)).slice(0, 3), "callback")
  },
  title: {
    description: "Full title, capitalized",
    callback: /* @__PURE__ */ __name((v) => capitalize(words(title(v))), "callback")
  },
  fulltitle: {
    description: "Full title, verbatim",
    callback: /* @__PURE__ */ __name((v) => words(title(v)), "callback")
  },
  year: {
    description: "Year",
    callback: /* @__PURE__ */ __name((v) => {
      const year = v.get("year")?.replace(/[^0-9]/g, "");
      return year ? [year] : [];
    }, "callback")
  },
  duplicateLetter: {
    description: "If the multiple entries end up with the same key, then insert a letter a-z. By default this will be inserted at the end.",
    callback: /* @__PURE__ */ __name((_, __, duplicate) => [duplicate ? numToLetter(duplicate) : ""], "callback")
  },
  duplicateNumber: {
    description: "If the multiple entries end up with the same key, then insert a number.",
    callback: /* @__PURE__ */ __name((_, __, duplicate) => [duplicate ? String(duplicate) : ""], "callback")
  }
};
function numToLetter(n) {
  return String.fromCharCode(96 + n);
}
__name(numToLetter, "numToLetter");
var MODIFIERS = {
  required: {
    description: "If data is missing, revert to existing key",
    callback: /* @__PURE__ */ __name((words2) => {
      if (words2.length === 0) throw new MissingRequiredData();
      return words2;
    }, "callback")
  },
  lower: {
    description: "Convert to lowercase",
    callback: /* @__PURE__ */ __name((words2) => words2.map((word) => word.toLocaleLowerCase()), "callback")
  },
  upper: {
    description: "Convert to uppercase",
    callback: /* @__PURE__ */ __name((words2) => words2.map((word) => word.toLocaleUpperCase()), "callback")
  },
  capitalize: {
    description: "Capitalize first letter of each word",
    callback: capitalize
  }
};
var MissingRequiredData = class extends Error {
  static {
    __name(this, "MissingRequiredData");
  }
};
function generateKeys(entries, cache, entryKeyTemplate) {
  let template = entryKeyTemplate;
  if (!entryKeyTemplate.includes("[duplicateLetter]") && !entryKeyTemplate.includes("[duplicateNumber]")) {
    template = `${entryKeyTemplate}[duplicateLetter]`;
  }
  const parsedTemplate = parseEntryKeyTemplate(template);
  const entriesByKey = /* @__PURE__ */ new Map();
  for (const entry of entries) {
    const entryValues = cache.lookupRenderedEntryValues(entry);
    const key = generateKey(entryValues, parsedTemplate);
    if (!key) continue;
    const entriesSoFar = entriesByKey.get(key) ?? [];
    entriesSoFar.push(entry);
    entriesByKey.set(key, entriesSoFar);
  }
  const keys = /* @__PURE__ */ new Map();
  for (const [key, entries2] of entriesByKey) {
    const regenerateDuplicate = entries2.length > 1;
    for (let i = 0; i < entries2.length; i++) {
      const node = entries2[i];
      if (!node) continue;
      const entryValues = cache.lookupRenderedEntryValues(node);
      const newKey = regenerateDuplicate ? generateKey(entryValues, parsedTemplate, i + 1) : key;
      if (!newKey) continue;
      keys.set(node, newKey);
    }
  }
  return keys;
}
__name(generateKeys, "generateKeys");
function generateKey(valueLookup, entryKeyTemplate, duplicateNumber) {
  try {
    let newKey = entryKeyTemplate.map((token) => {
      if (typeof token === "string") {
        return token;
      }
      const { marker, parameter, modifiers } = token;
      const specialMarker = SPECIAL_MARKERS[marker];
      let key;
      if (specialMarker) {
        key = specialMarker.callback(valueLookup, parameter, duplicateNumber);
      } else if (marker === marker.toLocaleUpperCase()) {
        const value = valueLookup.get(marker.toLocaleLowerCase());
        key = value ? words(value) : [];
      } else {
        throw new Error(`Invalid citation key token ${marker}`);
      }
      for (const modifierKey of modifiers) {
        const modifier = MODIFIERS[modifierKey];
        if (modifier) {
          key = modifier.callback(key);
        } else {
          throw new Error(`Invalid modifier ${modifierKey}`);
        }
      }
      return key.join("");
    }).join("");
    newKey = removeUnsafeEntryKeyChars(newKey);
    if (newKey === "") return;
    return newKey;
  } catch (e) {
    if (e instanceof MissingRequiredData) {
      return;
    }
    throw e;
  }
}
__name(generateKey, "generateKey");
var functionWords = /* @__PURE__ */ new Set([
  "a",
  "about",
  "above",
  "across",
  "against",
  "along",
  "among",
  "an",
  "and",
  "around",
  "at",
  "before",
  "behind",
  "below",
  "beneath",
  "beside",
  "between",
  "beyond",
  "but",
  "by",
  "down",
  "during",
  "except",
  "for",
  "for",
  "from",
  "in",
  "inside",
  "into",
  "like",
  "near",
  "nor",
  "of",
  "off",
  "on",
  "onto",
  "or",
  "since",
  "so",
  "the",
  "through",
  "to",
  "toward",
  "under",
  "until",
  "up",
  "upon",
  "with",
  "within",
  "without",
  "yet"
]);
function nonFunctionWords(value) {
  return words(value).filter(
    (word) => !functionWords.has(word.toLocaleLowerCase())
  );
}
__name(nonFunctionWords, "nonFunctionWords");
function words(value) {
  return value.split(/[\s.,:;]+/).filter((word) => word.length > 0);
}
__name(words, "words");
function capitalize(words2) {
  return words2.map(
    (word) => word.slice(0, 1).toLocaleUpperCase() + word.slice(1).toLocaleLowerCase()
  );
}
__name(capitalize, "capitalize");
function title(entryValues) {
  return entryValues.get("title") ?? entryValues.get("booktitle") ?? "";
}
__name(title, "title");
function removeUnsafeEntryKeyChars(str) {
  return str.replace(/[{},\s\\#%~()"'=.,:;[\]_]+/g, "");
}
__name(removeUnsafeEntryKeyChars, "removeUnsafeEntryKeyChars");

// src/transforms/generateKeys.ts
function createGenerateKeysTransform(template) {
  return {
    name: "generate-keys",
    apply: /* @__PURE__ */ __name((astProxy) => {
      const newKeys = generateKeys(astProxy.entries(), astProxy, template);
      for (const entry of astProxy.entries()) {
        const newKey = newKeys.get(entry);
        if (newKey) {
          entry.key = newKey;
        }
      }
      return void 0;
    }, "apply")
  };
}
__name(createGenerateKeysTransform, "createGenerateKeysTransform");

// src/transforms/indentFields.ts
function createIndentFieldsTransform(indent) {
  return {
    name: "indent",
    apply: /* @__PURE__ */ __name((astProxy) => {
      const fields = astProxy.fields();
      for (const field of fields) {
        field.whitespacePrefix = `
${indent}`;
      }
      return void 0;
    }, "apply")
  };
}
__name(createIndentFieldsTransform, "createIndentFieldsTransform");

// src/utils.ts
function convertCRLF(str) {
  return str.replace(/\r\n?/g, "\n");
}
__name(convertCRLF, "convertCRLF");
function wrapText(line, lineWidth) {
  const words2 = line.split(" ");
  const lines = [];
  let currLine = "";
  for (const [i, word] of words2.entries()) {
    if (currLine.length + word.length + 1 > lineWidth && i > 0) {
      lines.push(currLine.trim());
      currLine = "";
    }
    currLine += `${word} `;
  }
  return [...lines, currLine.trim()];
}
__name(wrapText, "wrapText");
function unwrapText(str) {
  return str.replace(/\s*\n\s*\n\s*/g, "<<BIBTEX_TIDY_PARA>>").replace(/\s*\n\s*/g, " ").replace(/<<BIBTEX_TIDY_PARA>>/g, "\n\n");
}
__name(unwrapText, "unwrapText");

// src/transforms/preferCurly.ts
function createPreferCurlyTransform() {
  return {
    name: "prefer-curly",
    apply: /* @__PURE__ */ __name((ast) => {
      for (const field of ast.fields()) {
        for (const child of field.value.concat) {
          child.type = "braced";
        }
        ast.invalidateField(field);
      }
      return void 0;
    }, "apply")
  };
}
__name(createPreferCurlyTransform, "createPreferCurlyTransform");

// src/transforms/removeDuplicateFields.ts
function createRemoveDuplicateFieldsTransform() {
  return {
    name: "remove-duplicate-fields",
    apply: /* @__PURE__ */ __name((astProxy) => {
      for (const node of astProxy.root().children) {
        if (node.type === "block" && node.block?.type === "entry") {
          const fieldSeen = /* @__PURE__ */ new Set();
          node.block.fields = node.block.fields.filter((field) => {
            const nameLc = field.name.toLocaleLowerCase();
            if (fieldSeen.has(nameLc)) {
              return false;
            }
            fieldSeen.add(nameLc);
            return true;
          });
        }
      }
      return void 0;
    }, "apply")
  };
}
__name(createRemoveDuplicateFieldsTransform, "createRemoveDuplicateFieldsTransform");

// src/transforms/removeEmptyFields.ts
function createRemoveEmptyFieldsTransform() {
  return {
    name: "remove-empty-fields",
    apply: /* @__PURE__ */ __name((ast) => {
      for (const node of ast.root().children) {
        if (node.type === "block" && node.block?.type === "entry") {
          const entry = node.block;
          entry.fields = entry.fields.filter(
            (field) => ast.lookupRenderedEntryValue(field) !== ""
          );
        }
      }
      return void 0;
    }, "apply")
  };
}
__name(createRemoveEmptyFieldsTransform, "createRemoveEmptyFieldsTransform");

// src/transforms/removeSpecifiedFields.ts
function createRemoveSpecifiedFieldsTransform(omit) {
  return {
    name: "remove-specified-fields",
    apply(ast) {
      const set = new Set(omit.map((f) => f.toLocaleLowerCase()));
      for (const field of ast.fields()) {
        if (set.has(field.name.toLocaleLowerCase())) {
          field.parent.fields = field.parent.fields.filter((f) => f !== field);
        }
      }
      return void 0;
    }
  };
}
__name(createRemoveSpecifiedFieldsTransform, "createRemoveSpecifiedFieldsTransform");

// src/transforms/resetWhitespace.ts
function createResetWhitespaceTransform(keepCommentWhitespace) {
  return {
    name: "reset-whitespace",
    apply: /* @__PURE__ */ __name((astProxy) => {
      const children = astProxy.root().children;
      let prev;
      for (const child of children) {
        const preserve = isComment2(child) && keepCommentWhitespace;
        const preservePrev = prev && isComment2(prev) && keepCommentWhitespace;
        if (keepCommentWhitespace && child.type === "block" && prev?.type === "text" && !prev.text.endsWith("\n")) {
          prev.text = `${prev.text.trimEnd()}
`;
        }
        if (!preserve) {
          child.whitespacePrefix = prev && !preservePrev ? "\n" : "";
          if (child.type === "text") {
            child.text = child.text.trim();
          } else if (child.block) {
            if (child.block.type === "entry") {
              for (const field of child.block.fields) {
                field.whitespacePrefix = "";
              }
            } else if (child.block.type === "comment") {
              child.block.raw = child.block.raw.trim();
            }
          }
        }
        prev = child;
      }
      return void 0;
    }, "apply")
  };
}
__name(createResetWhitespaceTransform, "createResetWhitespaceTransform");
function isComment2(node) {
  return node.type === "text" || node.block?.type === "comment";
}
__name(isComment2, "isComment");

// src/transforms/wrapValues.ts
function createWrapValuesTransform(indent, align, wrap) {
  return {
    name: "wrap-values",
    apply: /* @__PURE__ */ __name((astProxy) => {
      const fields = astProxy.fields();
      for (const field of fields) {
        for (const node of field.value.concat) {
          let value = unwrapText(node.value);
          if (node.type === "braced" && field.value.concat.length === 1) {
            value = value.trim();
          }
          if (node.type === "braced") {
            const lineLength = `${indent}${align}{${value}}`.length;
            const multiLine = value.includes("\n\n");
            if (wrap && lineLength > wrap || multiLine) {
              let paragraphs = value.split("\n\n");
              const valIndent = indent.repeat(2);
              if (wrap) {
                const wrapCol = wrap;
                paragraphs = paragraphs.map(
                  (paragraph) => wrapText(paragraph, wrapCol - valIndent.length).join(
                    `
${valIndent}`
                  )
                );
              }
              value = `
${valIndent}${paragraphs.join(`

${valIndent}`)}
${indent}`;
            }
            node.value = value;
          }
        }
      }
      return void 0;
    }, "apply")
  };
}
__name(createWrapValuesTransform, "createWrapValuesTransform");

// src/pipeline.ts
function sortPipeline(Transforms) {
  const sorted = [];
  const visited = /* @__PURE__ */ new Set();
  const visit = /* @__PURE__ */ __name((Transform) => {
    if (visited.has(Transform.name)) return;
    visited.add(Transform.name);
    for (const dep of Transform.dependencies ?? []) {
      const depTransform = Transforms.find((t) => t.name === dep);
      if (depTransform) visit(depTransform);
    }
    sorted.push(Transform);
  }, "visit");
  Transforms.forEach(visit);
  return sorted;
}
__name(sortPipeline, "sortPipeline");
function generateTransformPipeline(options) {
  const pipeline = [];
  if (options.months) {
    pipeline.push(createAbbreviateMonthsTransform());
  }
  pipeline.push(createRemoveDuplicateFieldsTransform());
  pipeline.push(createRemoveEmptyFieldsTransform());
  pipeline.push(createPreferCurlyTransform());
  pipeline.push(createRemoveSpecifiedFieldsTransform(["abstract"]));
  pipeline.push(createGenerateKeysTransform("[auth:required:lower][year:required][veryshorttitle:lower][duplicateNumber]"));
  pipeline.push(createDropAllCapsTransform());
  pipeline.push(createBlankLinesTransform());
  pipeline.push(createResetWhitespaceTransform(!options.tidyComments));
  const indent = options.tab ? "	" : " ".repeat(options.space);
  pipeline.push(createIndentFieldsTransform(indent));
  pipeline.push(createAlignValuesTransform(options.align));
  pipeline.push(createFieldCommasTransform(options.trailingCommas ?? false));
  pipeline.push(createWrapValuesTransform(indent, options.align, options.wrap));
  return sortPipeline(pipeline);
}
__name(generateTransformPipeline, "generateTransformPipeline");

// src/tidy.ts
var verbose = false;
function tidy(input, options_ = {}) {
  const options = normalizeOptions(options_);
  const inputFixed = convertCRLF(input);
  const ast = parseBibTeX(inputFixed);
  const cache = new ASTProxy(ast);
  const pipeline = generateTransformPipeline(options);
  const warnings = cache.entries().filter((entry) => !entry.key).map((entry) => ({
    code: "MISSING_KEY",
    message: `${entry.parent.command} entry does not have a citation key.`
  }));
  if (verbose) {
    console.log(logAST(ast));
  }
  for (const transform of pipeline) {
    const result = transform.apply(cache);
    if (verbose) {
      console.log(`

## Applying transform: ${transform.name}`);
      console.log(logAST(ast));
    }
    if (result) warnings.push(...result);
  }
  const bibtex = formatBibtex(ast);
  return { bibtex, warnings, count: cache.entries().length };
}
__name(tidy, "tidy");
export {
  tidy
};
